# Generated by Django 4.2 on 2024-09-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_comment_is_active_comment_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='published',
            new_name='recommend',
        ),
    ]
